const LOAD_ALL_STATES_SAGA = 'LOAD_ALL_STATES_SAGA';
const LOAD_ALL_EMPLOYEE_SAGA = 'LOAD_ALL_EMPLOYEE_SAGA';
const SET_ALL_STATES = "SET_ALL_STATES";
const SET_ALL_EMPLOYEES = "SET_ALL_EMPLOYEES";

export{
    LOAD_ALL_STATES_SAGA  ,
    LOAD_ALL_EMPLOYEE_SAGA ,
    SET_ALL_STATES ,
    SET_ALL_EMPLOYEES
}