// todo - rename this file
const HOST = 'http://localhost:3001'
export const FETCH_EMPLOYEE_URL = HOST + '/users/'
export const LOGIN_URL = HOST + '/users/login'
export const USER_AUTHENTICATION_URL = HOST + '/authorization'
export const FETCH_ALL_PROJECTS = HOST + '/projects'
export const FETCH_PEER_REVIEW = HOST + '/peersReview/'
export const FETCH_USER_PEER = HOST + '/peersReview/user'
export const CREATE_PEER_REVIEW = HOST + '/peersReview/add'
export const ADD_NEW_USER_URL = HOST + '/users/add'
export const DELETE_USER_URL = HOST + '/users/'
export const UPDATE_USER_URL = HOST + '/users/'
export const DELETE_PROJECT_URL = HOST + '/projects/'
export const ADD_NEW_PROJECT_URL = HOST + '/projects/add'
export const UPDATE_PROJECT_URL = HOST + '/projects/'
