// todo - rename this file
const HOST = 'http://localhost:3001'
export const FETCH_EMPLOYEE_URL = `${HOST}/users/`
export const LOGIN_URL = `${HOST}/users/login`
export const FETCH_MANAGER_URL = `${HOST}/users/managers`
export const USER_AUTHENTICATION_URL = `${HOST}/authorization`
export const FETCH_ALL_PROJECTS = `${HOST}/projects`
export const FETCH_PEER_REVIEW = `${HOST}/peersReview/`
export const FETCH_USER_PEER = `${HOST}/peersReview/user`
export const CREATE_PEER_REVIEW = `${HOST}/peersReview/add`
export const ADD_NEW_USER_URL = `${HOST}/users/add`
export const USER_URL = `${HOST}/users/`
export const PROJECT_URL = `${HOST}/projects/`
export const ADD_NEW_PROJECT_URL = `${HOST}/projects/add`
export const SELF_REVIEWS_URL = `${HOST}/review/`
export const CREATE_SELF_REVIEW = `${HOST}/add`
export const ALLOCATE_NEW_PROJECT_URL = `${HOST}/allocateProject/add`
export const ALLOCATE_PROJECT_URL = `${HOST}/allocateProject/`
export const FETCH_PEER_REVIEW_FOR_MANAGER = `${HOST}/peersReview/manager/employeePeer`
