const LOAD_ALL_EMPLOYEE_SAGA = 'LOAD_ALL_EMPLOYEE_SAGA'
const SET_ALL_EMPLOYEES = 'SET_ALL_EMPLOYEES'
const LOAD_ALL_PEER_SAGA = 'LOAD_ALL_PEER_SAGA'
const SET_ALL_PEER = 'SET_ALL_PEER'
const CREATE_PEER_SAGA = 'CREATE_PEER_SAGA'
const SET_PEER_SUCCESS_MESSAGE = 'CREATE_PEER_SUCCESS_MESSAGE'
const LOGIN_TO_SITE = 'LOGIN_TO_SITE'
const LOGIN_TO_SITE_SUCCESS = 'LOGIN_TO_SITE_SUCCESS'
const LOGOUT_FROM_SITE = 'LOGOUT_FROM_SITE'
const USER_ATHENTICATION = 'USER_ATHENTICATION'
const LOGIN_TO_SITE_ERROR = 'LOGIN_TO_SITE_ERROR'
const FETCH_ALL_PROJECTS_SAGA = 'FETCH_ALL_PROJECTS'
const SET_ALL_PROJECTS = 'SET_ALL_PROJECTS'

export {
  LOAD_ALL_EMPLOYEE_SAGA,
  SET_ALL_EMPLOYEES,
  LOGIN_TO_SITE,
  LOGIN_TO_SITE_SUCCESS,
  LOGIN_TO_SITE_ERROR,
  LOGOUT_FROM_SITE,
  USER_ATHENTICATION,
  LOAD_ALL_PEER_SAGA,
  SET_ALL_PEER,
  CREATE_PEER_SAGA,
  SET_PEER_SUCCESS_MESSAGE,
  FETCH_ALL_PROJECTS_SAGA,
  SET_ALL_PROJECTS
}
