const LOAD_ALL_EMPLOYEE_SAGA = 'LOAD_ALL_EMPLOYEE_SAGA'
const SET_ALL_EMPLOYEES = 'SET_ALL_EMPLOYEES'
const LOGIN_TO_SITE = 'LOGIN_TO_SITE'
const LOGIN_TO_SITE_SUCCESS = 'LOGIN_TO_SITE_SUCCESS'
const LOGOUT_FROM_SITE = 'LOGOUT_FROM_SITE'

export {
    LOAD_ALL_EMPLOYEE_SAGA,
    SET_ALL_EMPLOYEES,
    LOGIN_TO_SITE,
    LOGIN_TO_SITE_SUCCESS,
    LOGOUT_FROM_SITE
}
