const LOAD_ALL_EMPLOYEE_SAGA = 'LOAD_ALL_EMPLOYEE_SAGA'
const SET_ALL_EMPLOYEES = 'SET_ALL_EMPLOYEES'
const LOAD_ALL_PEER_SAGA = 'LOAD_ALL_PEER_SAGA'
const SET_ALL_PEER = 'SET_ALL_PEER'
const CREATE_PEER_SAGA = 'CREATE_PEER_SAGA'
const LOAD_ALL_USER_PEER_SAGA = 'LOAD_ALL_USER_PEER_SAGA'
const SET_ALL_USER_PEER = 'SET_ALL_USER_PEER'
const UPDATE_PEER_REVIEW = 'UPDATE_PEER_REVIEW'
const SET_PEER_REVIEW_UPDATE_STATUS = 'SET_PEER_REVIEW_UPDATE_STATUS'
const SET_PEER_SUCCESS_MESSAGE = 'CREATE_PEER_SUCCESS_MESSAGE'
const LOGIN_TO_SITE = 'LOGIN_TO_SITE'
const LOGIN_TO_SITE_SUCCESS = 'LOGIN_TO_SITE_SUCCESS'
const LOGOUT_FROM_SITE = 'LOGOUT_FROM_SITE'
const USER_ATHENTICATION = 'USER_ATHENTICATION'
const LOGIN_TO_SITE_ERROR = 'LOGIN_TO_SITE_ERROR'
const FETCH_ALL_PROJECTS_SAGA = 'FETCH_ALL_PROJECTS'
const SET_ALL_PROJECTS = 'SET_ALL_PROJECTS'
const ADD_NEW_USER = 'ADD_NEW_USER'
const SET_NEW_USER = 'SET_NEW_USER'
const SET_NEW_USER_ERROR = 'SET_NEW_USER_ERROR'
export const CLEAR_USER_STATUS_MESSAGE = 'CLEAR_USER_STATUS_MESSAGE'

export {
  LOAD_ALL_EMPLOYEE_SAGA,
  SET_ALL_EMPLOYEES,
  LOGIN_TO_SITE,
  LOGIN_TO_SITE_SUCCESS,
  LOGIN_TO_SITE_ERROR,
  LOGOUT_FROM_SITE,
  USER_ATHENTICATION,
  LOAD_ALL_PEER_SAGA,
  UPDATE_PEER_REVIEW,
  SET_PEER_REVIEW_UPDATE_STATUS,
  SET_ALL_PEER,
  CREATE_PEER_SAGA,
  SET_PEER_SUCCESS_MESSAGE,
  FETCH_ALL_PROJECTS_SAGA,
  SET_ALL_PROJECTS,
  LOAD_ALL_USER_PEER_SAGA,
  SET_ALL_USER_PEER,
  ADD_NEW_USER,
  SET_NEW_USER,
  SET_NEW_USER_ERROR
}
